#ifndef __PCM_HWPE_ARCHI__
#define __PCM_HWPE_ARCHI__

#define N_CFG_REGS 49

#define PCM_HWPE_BASE   0x0

#define PCM_HWPE_TRIG                   (PCM_HWPE_BASE + 0x00)
#define PCM_HWPE_ACQ                    (PCM_HWPE_BASE + 0x04)
#define PCM_HWPE_FIN_JOBS               (PCM_HWPE_BASE + 0x08)
#define PCM_HWPE_STATUS                 (PCM_HWPE_BASE + 0x0C)
#define PCM_HWPE_RUN_TASK               (PCM_HWPE_BASE + 0x10)
#define PCM_HWPE_SOFT_CLEAR             (PCM_HWPE_BASE + 0x14)
#define PCM_HWPE_CHK_STATE              (PCM_HWPE_BASE + 0x18)
#define PCM_HWPE_CFG_DIM                (PCM_HWPE_BASE + 0x1C)
#define PCM_HWPE_CFG_2S_U_COMP          (PCM_HWPE_BASE + 0x20)
#define PCM_HWPE_CFG_2S_U_2W_COMP       (PCM_HWPE_BASE + 0x24)
#define PCM_HWPE_CFG_2S_COMP            (PCM_HWPE_BASE + 0x28)
#define PCM_HWPE_CFG_2S_2W_COMP         (PCM_HWPE_BASE + 0x2C)
#define PCM_HWPE_CFG_SINGLE_STEP        (PCM_HWPE_BASE + 0x30)
#define PCM_HWPE_CFG_FAST_SINGLE_STEP   (PCM_HWPE_BASE + 0x34)
#define PCM_HWPE_CFG_INPUT_PRECISION    (PCM_HWPE_BASE + 0x38)
#define PCM_HWPE_CFG_BL_SETTINGS        (PCM_HWPE_BASE + 0x3C)
#define PCM_HWPE_JOB_START_X            (PCM_HWPE_BASE + 0x40)
#define PCM_HWPE_JOB_START_Y            (PCM_HWPE_BASE + 0x44)
#define PCM_HWPE_JOB_WIDTH              (PCM_HWPE_BASE + 0x48)
#define PCM_HWPE_JOB_HIGHT              (PCM_HWPE_BASE + 0x4C)
#define PCM_HWPE_JOB_SRC_ADDR           (PCM_HWPE_BASE + 0x50)
#define PCM_HWPE_JOB_DST_ADDR           (PCM_HWPE_BASE + 0x54)
#define PCM_HWPE_JOB_SRC_STRIDE         (PCM_HWPE_BASE + 0x58)
#define PCM_HWPE_JOB_DST_STRIDE         (PCM_HWPE_BASE + 0x5C)
#define PCM_HWPE_TOTAL_LENGTH           (PCM_HWPE_BASE + 0x60)
#define PCM_HWPE_D0_LENGTH              (PCM_HWPE_BASE + 0x64)
#define PCM_HWPE_D0_STRIDE              (PCM_HWPE_BASE + 0x68)
#define PCM_HWPE_D1_LENGTH              (PCM_HWPE_BASE + 0x6C)
#define PCM_HWPE_D1_STRIDE              (PCM_HWPE_BASE + 0x70)
#define PCM_HWPE_D2_STRIDE              (PCM_HWPE_BASE + 0x74)
#define PCM_HWPE_OUT_TOTAL_LENGTH       (PCM_HWPE_BASE + 0x78)
#define PCM_HWPE_OUT_D0_LENGTH          (PCM_HWPE_BASE + 0x7C)
#define PCM_HWPE_OUT_D0_STRIDE          (PCM_HWPE_BASE + 0x80)
#define PCM_HWPE_OUT_D1_LENGTH          (PCM_HWPE_BASE + 0x84)
#define PCM_HWPE_OUT_D1_STRIDE          (PCM_HWPE_BASE + 0x88)
#define PCM_HWPE_OUT_D2_STRIDE          (PCM_HWPE_BASE + 0x8C)
#define PCM_HWPE_NUM_JOBS               (PCM_HWPE_BASE + 0x90)
#define PCM_HWPE_ALPHA_IN_LENGTH        (PCM_HWPE_BASE + 0x94)
#define PCM_HWPE_ALPHA_IN_STRIDE        (PCM_HWPE_BASE + 0x98)
#define PCM_HWPE_BETA_IN_LENGTH         (PCM_HWPE_BASE + 0x9C)
#define PCM_HWPE_BETA_IN_STRIDE         (PCM_HWPE_BASE + 0xA0)
#define PCM_HWPE_ALPHA_OUT_LENGTH       (PCM_HWPE_BASE + 0xA4)
#define PCM_HWPE_ALPHA_OUT_STRIDE       (PCM_HWPE_BASE + 0xA8)
#define PCM_HWPE_BETA_OUT_LENGTH        (PCM_HWPE_BASE + 0xAC)
#define PCM_HWPE_BETA_OUT_STRIDE        (PCM_HWPE_BASE + 0xB0)
#define PCM_HWPE_JOB_LINE_LENGTH        (PCM_HWPE_BASE + 0xB4)
#define PCM_HWPE_ACT_SECT_3             (PCM_HWPE_BASE + 0xB8)
#define PCM_HWPE_ACT_SECT_2             (PCM_HWPE_BASE + 0xBC)
#define PCM_HWPE_ACT_SECT_1             (PCM_HWPE_BASE + 0xC0)
#define PCM_HWPE_ACT_SECT_0             (PCM_HWPE_BASE + 0xC4)
#define PCM_HWPE_ACT_LAYER              (PCM_HWPE_BASE + 0xC8)
#define PCM_HWPE_PRECISION              (PCM_HWPE_BASE + 0xCC)
#define PCM_HWPE_FIXED_TIME_COMP        (PCM_HWPE_BASE + 0xD0)
#define PCM_HWPE_HIGH_PREC_MASK         (PCM_HWPE_BASE + 0xD4)
#define PCM_HWPE_LOW_PREC_MASK          (PCM_HWPE_BASE + 0xD8)
#define PCM_HWPE_EN_CASTING             (PCM_HWPE_BASE + 0xDC)

#endif